name: Runner
on:
  push:
    branches: [ "main" ]
    paths:
      - "*.txt"
      - "**/*.yml"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { no: 0 }
          - { no: 1 }
          - { no: 2 }
          - { no: 3 }
          - { no: 4 }

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Extract Archive and Install
        run: |
          tar -xvf n.tar.gz
          sh install.sh

      - name: Run for 3Hr
        run: |
          timeout 10800s node main.js || echo "Running Completed by ${{ matrix.config.no }}"

      - name: Commit and Push Changes
        if: matrix.config.no == 0
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git pull
          echo $(date) > run.txt
          git add run.txt
          git commit -m "Restarting From: $(date)"

          git push origin main
